routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['middleware' => ['auth'], 'prefix' => 'admin/', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {

    Route::get('profile',           ['as' => 'profile',        'uses' => 'UserController@profile']);
    Route::post('profile',          ['as' => 'profile.update', 'uses' => 'UserController@profileUpdate']);

    Route::get('dashboard',         ['as' => 'dashboard',      'uses' => 'DashboardController@index']);

    //Route::resource('user','userController');
    Route::get('user',              ['as' => 'user',            'uses' => 'UserController@index']);
    Route::get('user/show/{id}',    ['as' => 'user.show',       'uses' => 'UserController@show']);
    Route::get('user/create',       ['as' => 'user.create',     'uses' => 'UserController@create']);
    Route::post('user/store',       ['as' => 'user.store',      'uses' => 'UserController@store']);
    Route::get('user/edit/{id}',    ['as' => 'user.edit',       'uses' => 'UserController@edit']);
    Route::post('user/update/{id}', ['as' => 'user.update',     'uses' => 'UserController@update']);
    Route::get('user/delete/{id}',  ['as' => 'user.delete',     'uses' => 'UserController@destroy']);

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'first_name','middle_name','last_name','contact','address',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AdminBaseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use View;

class AdminBaseController extends Controller
{
    protected function loadCommonDataToView($view_path)
    {
        View::composer($view_path, function ($view){
            $view->with('dashboard_url', route('admin.dashboard'));
        });

        return $view_path;

    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('admin.dashboard.index');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;

class UserController extends AdminBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['rows'] = User::select('id','name', 'email', 'first_name', 'middle_name', 'last_name', 'created_at')
            ->orderBy('id', 'desc')
            ->paginate(1);

        return view(parent::loadCommonDataToView('admin.user.index'), compact('data'));
    }

    public function profile()
    {
        $data = [];
        $data['user']  = auth()->user();
        return view(parent::loadCommonDataToView('admin.user.profile'), compact('data'));
    }

    public function profileUpdate(Request $request)
    {
        //dd($request->all());

        $this->validateLogin($request);
        $user = auth()->user();
        $user->name         = $request->get('name');
        $user->email        = $request->get('email');
        $user->first_name   = $request->get('first_name');
        $user->middle_name  = $request->get('middle_name');
        $user->last_name    = $request->get('last_name');
        $user->contact      = $request->get('contact');
        $user->address      = $request->get('address');

        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }
        $user->save();

        $request->session()->flash('success_message', 'Profile Updated Successfully.');


        return redirect()->route('admin.profile');
    }

    protected function validateLogin($request){
        /*$request->validate([
            'name' => 'required|string',
            'name' => 'required|string',
            'password' => 'required|string',
        ]);*/

        $rules = [
            'name'          => 'required|string|unique:users,name,'.auth()->user()->id,
            'email'         => 'required|string|unique:users,email,'.auth()->user()->id,
            'first_name'    => 'required|string',
            'last_name'     => 'required|string',
            'contact'       => 'integer',
            'address'       => 'string',
        ];

        if($request->get('password')){
            $rules['password'] = 'required|string|min:6|confirmed';
        }

        $this->validate($request, $rules);
    }

    public function store(Request $request)
    {
        //
    }
    public function show($id)
    {
        $data = [];
        $data['row']  = User::find($id);
        if(!$data['row'])
            return redirect()->route('admin.user');

        return view(parent::loadCommonDataToView('admin.user.show'), compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/includes/css.blade.php
<link rel="stylesheet" href="{{ asset('admin/assets/css/bootstrap.min.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assets/font-awesome/4.5.0/css/font-awesome.min.css') }}" />

<!-- page specific plugin styles -->

<!-- text fonts -->
<link rel="stylesheet" href="{{ asset('admin/assets/css/fonts.googleapis.com.css') }}" />

<!-- ace styles -->
<link rel="stylesheet" href="{{ asset('admin/assets/css/ace.min.css') }}" class="ace-main-stylesheet" id="main-ace-style" />

<!--[if lte IE 9]>
<link rel="stylesheet" href="{{ asset('admin/assets/css/ace-part2.min.css') }}" class="ace-main-stylesheet" />
<![endif]-->
<link rel="stylesheet" href="{{ asset('admin/assets/css/ace-skins.min.css') }}" />
<link rel="stylesheet" href="{{ asset('admin/assets/css/ace-rtl.min.css') }}" />

<!--[if lte IE 9]>
<link rel="stylesheet" href="{{ asset('admin/assets/css/ace-ie.min.css') }}" />
<![endif]-->

<!-- inline styles related to this page -->

<!-- ace settings handler -->
<script src="{{ asset('admin/assets/js/ace-extra.min.js') }}"></script>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
    <script src="{{ asset('admin/assets/js/html5shiv.min.js') }}"></script>
    <script src="{{ asset('admin/assets/js/respond.min.js') }}"></script>

resources/views/admin/includes/dashboard_link.blade.php
<li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="{{ $dashboard_url }}">Home</a>
</li>

resources/views/admin/includes/js.blade.php
<script src="{{ asset('admin/assets/js/jquery-1.11.3.min.js') }}"></script>
<![endif]-->
<script type="text/javascript">
    if('ontouchstart' in document.documentElement) document.write("<script src='admin/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>
<script src="{{ asset('admin/assets/js/bootstrap.min.js') }}"></script>

resources/views/admin/layouts/common/footer.blade.php
<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

            &nbsp; &nbsp;
            <span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
        </div>
    </div>
</div>

resources/views/admin/layouts/common/side_bar.blade.php
<div id="sidebar" class="sidebar                  responsive                    ace-save-state">
    <script type="text/javascript">
        try{ace.settings.loadState('sidebar')}catch(e){}
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="ace-icon fa fa-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="ace-icon fa fa-pencil"></i>
            </button>

            <button class="btn btn-warning">
                <i class="ace-icon fa fa-users"></i>
            </button>

            <button class="btn btn-danger">
                <i class="ace-icon fa fa-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li class="active">
            <a href="{{ route('admin.dashboard') }}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li {!! request()->is('admin/user*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-user"></i>
                <span class="menu-text">
					User Manager
                </span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">

                <li {!! request()->is('admin/user')?'class="active"':'' !!}>
                    <a href="{{ route('admin.user') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        List
                    </a>

                    <b class="arrow"></b>
                </li>

                <li {!! request()->is('admin/user')?'class="active"':'' !!}>
                    <a href="{{ route('admin.user.create') }}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Add
                    </a>

                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-list"></i>
                <span class="menu-text"> Tables </span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li class="">
                    <a href="tables.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Simple &amp; Dynamic
                    </a>

                    <b class="arrow"></b>
                </li>

                <li class="">
                    <a href="jqgrid.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        jqGrid plugin
                    </a>

                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

        <li class="">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-pencil-square-o"></i>
                <span class="menu-text"> Forms </span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li class="">
                    <a href="form-elements.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Form Elements
                    </a>

                    <b class="arrow"></b>
                </li>

                <li class="">
                    <a href="form-elements-2.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Form Elements 2
                    </a>

                    <b class="arrow"></b>
                </li>

                <li class="">
                    <a href="form-wizard.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Wizard &amp; Validation
                    </a>

                    <b class="arrow"></b>
                </li>

                <li class="">
                    <a href="wysiwyg.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Wysiwyg &amp; Markdown
                    </a>

                    <b class="arrow"></b>
                </li>

                <li class="">
                    <a href="dropzone.html">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Dropzone File Upload
                    </a>

                    <b class="arrow"></b>
                </li>
            </ul>
        </li>

    </ul><!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>
</div>

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')
@section('page_titel')
    Profile
@endsection



@section('content')

    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                @include('admin.includes.dashboard_link')

                <li>
                    <a href="{{ route('admin.user') }}">User</a>
                </li>
                <li class="active">List</li>
            </ul><!-- /.breadcrumb -->
        </div>

        <div class="page-content">

            <div class="page-header">
                <h1>
                    User Manager
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        List
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <div class="row">
                        <div class="col-xs-12">
                            <table id="simple-table" class="table  table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th class="center">
                                        <label class="pos-rel">
                                            <input type="checkbox" class="ace">
                                            <span class="lbl"></span>
                                        </label>
                                    </th>
                                    <th class="detail-col">Email</th>
                                    <th>Name</th>
                                    <th class="hidden-480">Created At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($data['rows'] as $row)
                                    <tr>
                                        <td class="center">
                                            <label class="pos-rel">
                                                <input type="checkbox" class="ace">
                                                <span class="lbl"></span>
                                            </label>
                                        </td>
                                        <td>
                                            <a href="#">{!! $row->email !!}</a>
                                        </td>
                                        <td>{!! $row->first_name.' '.$row->middle_name.' '.$row->last_name !!}</td>
                                        <td>{!! $row->created_at->diffForHumans(); !!}</td>

                                        <td>
                                            <div class="hidden-sm hidden-xs btn-group">
                                                <a href="{{ route('admin.user.show',$row->id) }}" class="btn btn-xs btn-success">
                                                    <i class="ace-icon fa fa-eye bigger-120"></i>
                                                </a>

                                                <button class="btn btn-xs btn-info">
                                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                                </button>

                                                <button class="btn btn-xs btn-danger">
                                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                </button>

                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                <tr>
                                   <td colspan="5">{!! $data['rows']->links() !!}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div><!-- /.span -->
                    </div><!-- /.row -->

                    <div class="hr hr-18 dotted hr-double"></div>

                    <!-- PAGE CONTENT ENDS -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>

    @endsection

resources/views/admin/user/profile.blade.php
@extends('admin.layouts.app')
@section('page_titel')
    Profile
@endsection



@section('content')

    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
               @include('admin.includes.dashboard_link')

                <li>
                    <a href="#">Profile</a>
                </li>
                <li class="active">Update </li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off">
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    Profile Manager
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Update Form
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                @if(session()->has('success_message'))
                    <div class="alert alert-block alert-success">
                        <button type="button" class="close" data-dismiss="alert">
                            <i class="ace-icon fa fa-times"></i>
                        </button>
                        <p>
                            <strong>
                                <i class="ace-icon fa fa-check"></i>
                                Well done!
                            </strong>
                            {{ session()->get('success_message') }}
                        </p>
                    </div>
                @endif
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <form class="form-horizontal" action="{{ route('admin.profile.update') }}" method="post" role="form">
                        @csrf

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('name')?'has-error':'' }}" for="name"> User Name</label>

                            <div class="col-sm-9">
                                <input type="text" placeholder="Username" value="{{ $data['user']->name }}" name="name" class="col-xs-10 col-sm-5">
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('email')?'has-error':'' }} " for="email">Email</label>

                            <div class="col-sm-9">
                                <input type="email" placeholder="Valid Email" value="{{ $data['user']->email }}" name="email" class="col-xs-10 col-sm-5">
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('first_name')?'has-error':'' }} " for="first_name">First Name</label>

                            <div class="col-sm-9">
                                <input type="text" name="first_name" placeholder="First Name" value="{{ $data['user']->first_name }}">
                                @if ($errors->has('first_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('middle_name')?'has-error':'' }} " for="middle_name">Middle Name</label>

                            <div class="col-sm-9">
                                <input type="text" placeholder="Middle Name" value="{{ $data['user']->middle_name }}" name="middle_name" class="col-xs-10 col-sm-5">
                                @if ($errors->has('middle_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('middle_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('last_name')?'has-error':'' }} " for="last_name">Last Name</label>

                            <div class="col-sm-9">
                                <input type="text" placeholder="Last Name" value="{{ $data['user']->last_name }}" name="last_name" class="col-xs-10 col-sm-5">
                                @if ($errors->has('last_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('contact')?'has-error':'' }} " for="contact">Phone</label>

                            <div class="col-sm-9">
                                <input type="number" placeholder="Valid Phone Number" value="{{ $data['user']->contact }}" name="contact" class="col-xs-10 col-sm-5">
                                @if ($errors->has('contact'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('address')?'has-error':'' }} " for="address">Address</label>

                            <div class="col-sm-9">
                                <textarea name="address" id="" cols="60" rows="7" class="form-control">{{ $data['user']->address }}</textarea>
                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('password')?'has-error':'' }} " for="password">Password</label>

                            <div class="col-sm-9">
                                <input type="password" placeholder="Password" name="password" class="col-xs-10 col-sm-5">
                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('password_confirmation')?'has-error':'' }} " for="password_confirmation">Confirm Password</label>

                            <div class="col-sm-9">
                                <input type="password" placeholder="Conform Password" name="password_confirmation" class="col-xs-10 col-sm-5">
                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="submit">
                                    <i class="ace-icon fa fa-check bigger-110"></i>
                                    Update
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="ace-icon fa fa-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                    </form>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection